version: '3.3'
services:
  stirling-pdf:
    image: stirlingtools/stirling-pdf:latest
    restart: unless-stopped
    ports:
      - '8344:8080'
    volumes:
      - /home/josh/docker/sterlingpdf/trainingData:/usr/share/tessdata # Required for extra OCR languages
      - /home/josh/docker/sterlingpdf/extraConfigs:/configs
      - /home/josh/docker/sterlingpdf/customFiles:/customFiles/
      - /home/josh/docker/sterlingpdf/logs:/logs/
      - /home/josh/docker/sterlingpdf/pipeline:/pipeline/
    environment:
      - DOCKER_ENABLE_SECURITY=false
      - INSTALL_BOOK_AND_ADVANCED_HTML_OPS=false
      - LANGS=en_GB
